repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
    -   id: check-byte-order-marker
    -   id: check-case-conflict
    -   id: check-merge-conflict
    -   id: check-symlinks
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: mixed-line-ending
    -   id: trailing-whitespace
-   repo: https://github.com/pre-commit/pre-commit
    rev: v2.16.0
    hooks:
    -   id: validate_manifest
-   repo: https://github.com/antisvin/owl_wave
    rev: 527363b9a68d620b7122987f48057050244584a8
    hooks:
    -   id: fmt
    -   id: cargo-check
    -   id: clippy
    -   id: rebuild-web
